version: '2'


services:

   mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql:/var/lib/mysql
